# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Luchini, Tiago
email: info@tiagoluchini.eu
description: > # this means to ignore newlines until "baseurl:"
  I build <a href="https://work.co">digital products</a> people use everyday.
  Avid <a href="https://instagram.com/tiagoruns">distance runner</a>, Open Source
  supporter, software engineer at heart, business by
  <a href="https://www.linkedin.com/in/tiagoluchini#education">training</a>, and
  <a href="https://boardgamegeek.com/user/tiagoluchini">board game</a> enthusiast.
  Partner, Technology @ <a href="https://work.co">work.co</a>.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tiagoluchini
github_username: luchiniatwork

google_analytics: UA-105784466-1

urls:
  github: https://github.com/luchiniatwork
  twitter: https://twitter.com/tiagoluchini
  instagram: https://instagram.com/tiagoruns
  linkedin: https://www.linkedin.com/in/tiagoluchini

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
